USE ${hiveconf:DB_NAME};

SET hive.exec.dynamic.partition=true;
SET hive.exec.dynamic.partition.mode=nonstrict;

-- partitioned by state, bucketed by severity (4 buckets for the 4 severity levels)
CREATE EXTERNAL TABLE IF NOT EXISTS us_accidents_part_buck (
  id               STRING,
  source           STRING,
  severity         INT,
  start_time       TIMESTAMP,
  end_time         TIMESTAMP,
  start_lat        DOUBLE,
  start_lng        DOUBLE,
  end_lat          DOUBLE,
  end_lng          DOUBLE,
  distance_mi      DOUBLE,
  description      STRING,
  street           STRING,
  city             STRING,
  county           STRING,
  zipcode          STRING,
  country          STRING,
  timezone         STRING,
  airport_code     STRING,
  weather_timestamp TIMESTAMP,
  temperature_f    DOUBLE,
  wind_chill_f     DOUBLE,
  humidity_pct     DOUBLE,
  pressure_in      DOUBLE,
  visibility_mi    DOUBLE,
  wind_direction   STRING,
  wind_speed_mph   DOUBLE,
  precipitation_in DOUBLE,
  weather_condition STRING,
  amenity          BOOLEAN,
  bump             BOOLEAN,
  crossing         BOOLEAN,
  give_way         BOOLEAN,
  junction         BOOLEAN,
  no_exit          BOOLEAN,
  railway          BOOLEAN,
  roundabout       BOOLEAN,
  station          BOOLEAN,
  stop             BOOLEAN,
  traffic_calming  BOOLEAN,
  traffic_signal   BOOLEAN,
  turning_loop     BOOLEAN,
  sunrise_sunset   STRING,
  civil_twilight   STRING,
  nautical_twilight STRING,
  astronomical_twilight STRING
)
PARTITIONED BY (state STRING)
CLUSTERED BY (severity) INTO 4 BUCKETS
STORED AS ORC
LOCATION '${hiveconf:HIVE_WAREHOUSE_LOC}/us_accidents_part_buck'
TBLPROPERTIES ('orc.compress'='SNAPPY');

-- populate from the unpartitioned external table partitioned by state key
INSERT OVERWRITE TABLE us_accidents_part_buck PARTITION (state)
SELECT
  id,
  source,
  CAST(severity AS INT),
  CAST(start_time AS TIMESTAMP),
  CAST(end_time AS TIMESTAMP),
  start_lat,
  start_lng,
  end_lat,
  end_lng,
  distance_mi,
  description,
  street,
  city,
  county,
  zipcode,
  country,
  timezone,
  airport_code,
  CAST(weather_timestamp AS TIMESTAMP),
  temperature_f,
  wind_chill_f,
  humidity_pct,
  pressure_in,
  visibility_mi,
  wind_direction,
  wind_speed_mph,
  precipitation_in,
  weather_condition,
  amenity,
  bump,
  crossing,
  give_way,
  junction,
  no_exit,
  railway,
  roundabout,
  station,
  stop,
  traffic_calming,
  traffic_signal,
  turning_loop,
  sunrise_sunset,
  civil_twilight,
  nautical_twilight,
  astronomical_twilight,
  state
FROM us_accidents
WHERE state IS NOT NULL;
